### ISSUE TITLE
Exception while running this example

### ISSUE THREAD

**Issue by darshan87** [dmagda/MicroServicesExample#1]
I am getting following exception when I run TestAppStartup.java

Aug 10, 2017 6:36:32 PM org.apache.ignite.logger.java.JavaLogger error
SEVERE: Failed to execute job [jobId=e28d04ccd51-ef858df5-1e77-4cd3-b8ce-9fd865c73755, ses=GridJobSessionImpl [ses=GridTaskSessionImpl [taskName=o.a.i.i.processors.service.GridServiceProxy$ServiceProxyCallable, dep=GridDeployment [ts=1502369296643, depMode=SHARED, clsLdr=sun.misc.Launcher$AppClassLoader@73d16e93, clsLdrId=46b203ccd51-6c57bc72-8fe6-49a8-881b-f373981ca551, userVer=0, loc=true, sampleClsName=o.a.i.i.processors.cache.distributed.dht.preloader.GridDhtPartitionFullMap, pendingUndeploy=false, undeployed=false, usage=1], taskClsName=o.a.i.i.processors.service.GridServiceProxy$ServiceProxyCallable, sesId=d28d04ccd51-ef858df5-1e77-4cd3-b8ce-9fd865c73755, startTime=1502370392789, endTime=9223372036854775807, taskNodeId=ef858df5-1e77-4cd3-b8ce-9fd865c73755, clsLdr=sun.misc.Launcher$AppClassLoader@73d16e93, closed=false, cpSpi=null, failSpi=null, loadSpi=null, usage=1, fullSup=false, internal=false, subjId=ef858df5-1e77-4cd3-b8ce-9fd865c73755, mapFut=IgniteFuture [orig=GridFutureAdapter [resFlag=0, res=null, startTime=1502370392791, endTime=0, ignoreInterrupts=false, state=INIT]]], jobId=e28d04ccd51-ef858df5-1e77-4cd3-b8ce-9fd865c73755]]
class org.apache.ignite.IgniteException: null
	at org.apache.ignite.internal.processors.closure.GridClosureProcessor$C2V2.execute(GridClosureProcessor.java:2059)
	at org.apache.ignite.internal.processors.job.GridJobWorker$2.call(GridJobWorker.java:560)
	at org.apache.ignite.internal.util.IgniteUtils.wrapThreadLoader(IgniteUtils.java:6618)
	at org.apache.ignite.internal.processors.job.GridJobWorker.execute0(GridJobWorker.java:554)
	at org.apache.ignite.internal.processors.job.GridJobWorker.body(GridJobWorker.java:483)
	at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:110)
	at org.apache.ignite.internal.processors.job.GridJobProcessor.processJobExecuteRequest(GridJobProcessor.java:1180)
	at org.apache.ignite.internal.processors.job.GridJobProcessor$JobExecutionListener.onMessage(GridJobProcessor.java:1894)
	at org.apache.ignite.internal.managers.communication.GridIoManager.invokeListener(GridIoManager.java:1222)
	at org.apache.ignite.internal.managers.communication.GridIoManager.processRegularMessage0(GridIoManager.java:850)
	at org.apache.ignite.internal.managers.communication.GridIoManager.access$2100(GridIoManager.java:108)
	at org.apache.ignite.internal.managers.communication.GridIoManager$7.run(GridIoManager.java:790)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.ignite.internal.processors.service.GridServiceProxy$ServiceProxyCallable.call(GridServiceProxy.java:406)
	at org.apache.ignite.internal.processors.closure.GridClosureProcessor$C2V2.execute(GridClosureProcessor.java:2056)
	... 14 more
Caused by: org.apache.ignite.cache.CachePartialUpdateException: Failed to update keys (retry update if possible).: [8]
	at org.apache.ignite.internal.processors.cache.GridCacheUtils.convertToCacheException(GridCacheUtils.java:1429)
	at org.apache.ignite.internal.processors.cache.IgniteCacheProxy.cacheException(IgniteCacheProxy.java:2182)
	at org.apache.ignite.internal.processors.cache.IgniteCacheProxy.put(IgniteCacheProxy.java:1382)
	at services.maintenance.MaintenanceServiceImpl.scheduleVehicleMaintenance(MaintenanceServiceImpl.java:104)
	... 20 more
Caused by: class org.apache.ignite.internal.processors.cache.CachePartialUpdateCheckedException: Failed to update keys (retry update if possible).: [8]
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridNearAtomicSingleUpdateFuture.onResult(GridNearAtomicSingleUpdateFuture.java:229)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.processNearAtomicUpdateResponse(GridDhtAtomicCache.java:3199)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.access$1700(GridDhtAtomicCache.java:126)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache$7.apply(GridDhtAtomicCache.java:356)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache$7.apply(GridDhtAtomicCache.java:351)
	at org.apache.ignite.internal.processors.cache.GridCacheIoManager.processMessage(GridCacheIoManager.java:827)
	at org.apache.ignite.internal.processors.cache.GridCacheIoManager.onMessage0(GridCacheIoManager.java:369)
	at org.apache.ignite.internal.processors.cache.GridCacheIoManager.handleMessage(GridCacheIoManager.java:293)
	at org.apache.ignite.internal.processors.cache.GridCacheIoManager.access$000(GridCacheIoManager.java:95)
	at org.apache.ignite.internal.processors.cache.GridCacheIoManager$1.onMessage(GridCacheIoManager.java:238)
	at org.apache.ignite.internal.managers.communication.GridIoManager.invokeListener(GridIoManager.java:1222)
	at org.apache.ignite.internal.managers.communication.GridIoManager.processRegularMessage0(GridIoManager.java:850)
	at org.apache.ignite.internal.managers.communication.GridIoManager.access$2100(GridIoManager.java:108)
	at org.apache.ignite.internal.managers.communication.GridIoManager$7.run(GridIoManager.java:790)
	at org.apache.ignite.internal.util.StripedExecutor$Stripe.run(StripedExecutor.java:428)
	... 1 more
	Suppressed: class org.apache.ignite.IgniteCheckedException: Failed to update keys on primary node.
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridNearAtomicUpdateResponse.addFailedKey(GridNearAtomicUpdateResponse.java:350)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.updateSingle(GridDhtAtomicCache.java:2620)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.updateAllAsyncInternal0(GridDhtAtomicCache.java:1881)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.updateAllAsyncInternal(GridDhtAtomicCache.java:1721)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.processNearAtomicUpdateRequest(GridDhtAtomicCache.java:3181)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.access$1600(GridDhtAtomicCache.java:126)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache$6.apply(GridDhtAtomicCache.java:338)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache$6.apply(GridDhtAtomicCache.java:333)
		... 11 more
		Suppressed: class org.apache.ignite.IgniteCheckedException: Cache store must work with binary objects if binary are enabled for cache [cacheName=maintenance]
			at org.apache.ignite.internal.processors.cache.store.GridCacheStoreManagerAdapter.handleClassCastException(GridCacheStoreManagerAdapter.java:811)
			at org.apache.ignite.internal.processors.cache.store.GridCacheStoreManagerAdapter.put(GridCacheStoreManagerAdapter.java:584)
			at org.apache.ignite.internal.processors.cache.GridCacheMapEntry.innerUpdate(GridCacheMapEntry.java:2507)
			at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.updateSingle(GridDhtAtomicCache.java:2479)
			... 17 more
		Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
			at common.cachestore.SimpleCacheStore.write(SimpleCacheStore.java:52)
			at org.apache.ignite.internal.processors.cache.store.GridCacheStoreManagerAdapter.put(GridCacheStoreManagerAdapter.java:579)
			... 19 more

**Comment by tvvignesh** [comment]
I get the same error as well

```
Jan 03, 2018 6:50:29 PM org.apache.ignite.logger.java.JavaLogger error
SEVERE: Failed to obtain remote job result policy for result from ComputeTask.result(..) method (will fail the whole task): GridJobResultImpl [job=C2V2 [c=ServiceProxyCallable [mtdName=scheduleVehicleMaintenance, svcName=MaintenanceService, ignite=null]], sib=GridJobSiblingImpl [sesId=7d81e2cb061-18c24fc2-dbe7-40cb-8032-f6b33ef67c3a, jobId=8d81e2cb061-18c24fc2-dbe7-40cb-8032-f6b33ef67c3a, nodeId=6177e29a-0c26-481f-bdb0-bddc578622f5, isJobDone=false], jobCtx=GridJobContextImpl [jobId=8d81e2cb061-18c24fc2-dbe7-40cb-8032-f6b33ef67c3a, timeoutObj=null, attrs={}], node=TcpDiscoveryNode [id=6177e29a-0c26-481f-bdb0-bddc578622f5, addrs=[0:0:0:0:0:0:0:1%lo, 10.10.36.20, 127.0.0.1, 172.17.0.1], sockAddrs=[/10.10.36.20:47501, /0:0:0:0:0:0:0:1%lo:47501, /127.0.0.1:47501, /172.17.0.1:47501], discPort=47501, order=2, intOrder=2, lastExchangeTime=1514985627648, loc=false, ver=1.9.0#20170302-sha1:a8169d0a, isClient=false], ex=class o.a.i.IgniteException: null, hasRes=true, isCancelled=false, isOccupied=true]
class org.apache.ignite.IgniteException: Remote job threw user exception (override or implement ComputeTask.result(..) method if you would like to have automatic failover for this exception).
	at org.apache.ignite.compute.ComputeTaskAdapter.result(ComputeTaskAdapter.java:101)
	at org.apache.ignite.internal.processors.task.GridTaskWorker$5.apply(GridTaskWorker.java:1031)
	at org.apache.ignite.internal.processors.task.GridTaskWorker$5.apply(GridTaskWorker.java:1024)
	at org.apache.ignite.internal.util.IgniteUtils.wrapThreadLoader(IgniteUtils.java:6650)
	at org.apache.ignite.internal.processors.task.GridTaskWorker.result(GridTaskWorker.java:1024)
	at org.apache.ignite.internal.processors.task.GridTaskWorker.onResponse(GridTaskWorker.java:842)
	at org.apache.ignite.internal.processors.task.GridTaskProcessor.processJobExecuteResponse(GridTaskProcessor.java:996)
	at org.apache.ignite.internal.processors.task.GridTaskProcessor$JobMessageListener.onMessage(GridTaskProcessor.java:1221)
	at org.apache.ignite.internal.managers.communication.GridIoManager.invokeListener(GridIoManager.java:1222)
	at org.apache.ignite.internal.managers.communication.GridIoManager.processRegularMessage0(GridIoManager.java:850)
	at org.apache.ignite.internal.managers.communication.GridIoManager.access$2100(GridIoManager.java:108)
	at org.apache.ignite.internal.managers.communication.GridIoManager$7.run(GridIoManager.java:790)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: class org.apache.ignite.IgniteException: null
	at org.apache.ignite.internal.processors.closure.GridClosureProcessor$C2V2.execute(GridClosureProcessor.java:2059)
	at org.apache.ignite.internal.processors.job.GridJobWorker$2.call(GridJobWorker.java:560)
	at org.apache.ignite.internal.util.IgniteUtils.wrapThreadLoader(IgniteUtils.java:6618)
	at org.apache.ignite.internal.processors.job.GridJobWorker.execute0(GridJobWorker.java:554)
	at org.apache.ignite.internal.processors.job.GridJobWorker.body(GridJobWorker.java:483)
	at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:110)
	at org.apache.ignite.internal.processors.job.GridJobProcessor.processJobExecuteRequest(GridJobProcessor.java:1180)
	at org.apache.ignite.internal.processors.job.GridJobProcessor$JobExecutionListener.onMessage(GridJobProcessor.java:1894)
	... 7 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ignite.internal.processors.service.GridServiceProxy$ServiceProxyCallable.call(GridServiceProxy.java:406)
	at org.apache.ignite.internal.processors.closure.GridClosureProcessor$C2V2.execute(GridClosureProcessor.java:2056)
	... 14 more
Caused by: org.apache.ignite.cache.CachePartialUpdateException: Failed to update keys (retry update if possible).: [1]
	at org.apache.ignite.internal.processors.cache.GridCacheUtils.convertToCacheException(GridCacheUtils.java:1429)
	at org.apache.ignite.internal.processors.cache.IgniteCacheProxy.cacheException(IgniteCacheProxy.java:2182)
	at org.apache.ignite.internal.processors.cache.IgniteCacheProxy.put(IgniteCacheProxy.java:1382)
	at services.maintenance.MaintenanceServiceImpl.scheduleVehicleMaintenance(MaintenanceServiceImpl.java:104)
	... 20 more
Caused by: class org.apache.ignite.internal.processors.cache.CachePartialUpdateCheckedException: Failed to update keys (retry update if possible).: [1]
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridNearAtomicSingleUpdateFuture.onResult(GridNearAtomicSingleUpdateFuture.java:229)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.processNearAtomicUpdateResponse(GridDhtAtomicCache.java:3199)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.access$1700(GridDhtAtomicCache.java:126)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache$7.apply(GridDhtAtomicCache.java:356)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache$7.apply(GridDhtAtomicCache.java:351)
	at org.apache.ignite.internal.processors.cache.GridCacheIoManager.processMessage(GridCacheIoManager.java:827)
	at org.apache.ignite.internal.processors.cache.GridCacheIoManager.onMessage0(GridCacheIoManager.java:369)
	at org.apache.ignite.internal.processors.cache.GridCacheIoManager.handleMessage(GridCacheIoManager.java:293)
	at org.apache.ignite.internal.processors.cache.GridCacheIoManager.access$000(GridCacheIoManager.java:95)
	at org.apache.ignite.internal.processors.cache.GridCacheIoManager$1.onMessage(GridCacheIoManager.java:238)
	at org.apache.ignite.internal.managers.communication.GridIoManager.invokeListener(GridIoManager.java:1222)
	at org.apache.ignite.internal.managers.communication.GridIoManager.processRegularMessage0(GridIoManager.java:850)
	at org.apache.ignite.internal.managers.communication.GridIoManager.access$2100(GridIoManager.java:108)
	at org.apache.ignite.internal.managers.communication.GridIoManager$7.run(GridIoManager.java:790)
	at org.apache.ignite.internal.util.StripedExecutor$Stripe.run(StripedExecutor.java:428)
	... 1 more
	Suppressed: class org.apache.ignite.IgniteCheckedException: Failed to update keys on primary node.
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridNearAtomicUpdateResponse.addFailedKey(GridNearAtomicUpdateResponse.java:350)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.updateSingle(GridDhtAtomicCache.java:2620)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.updateAllAsyncInternal0(GridDhtAtomicCache.java:1881)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.updateAllAsyncInternal(GridDhtAtomicCache.java:1721)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.processNearAtomicUpdateRequest(GridDhtAtomicCache.java:3181)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.access$1600(GridDhtAtomicCache.java:126)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache$6.apply(GridDhtAtomicCache.java:338)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache$6.apply(GridDhtAtomicCache.java:333)
		... 11 more
		Suppressed: class org.apache.ignite.IgniteCheckedException: Cache store must work with binary objects if binary are enabled for cache [cacheName=maintenance]
			at org.apache.ignite.internal.processors.cache.store.GridCacheStoreManagerAdapter.handleClassCastException(GridCacheStoreManagerAdapter.java:811)
			at org.apache.ignite.internal.processors.cache.store.GridCacheStoreManagerAdapter.put(GridCacheStoreManagerAdapter.java:584)
			at org.apache.ignite.internal.processors.cache.GridCacheMapEntry.innerUpdate(GridCacheMapEntry.java:2507)
			at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.updateSingle(GridDhtAtomicCache.java:2479)
			... 17 more
		Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
			at common.cachestore.SimpleCacheStore.write(SimpleCacheStore.java:52)
			at org.apache.ignite.internal.processors.cache.store.GridCacheStoreManagerAdapter.put(GridCacheStoreManagerAdapter.java:579)
			... 19 more

Exception in thread "main" class org.apache.ignite.IgniteException: null
	at org.apache.ignite.internal.util.IgniteUtils.convertException(IgniteUtils.java:946)
	at org.apache.ignite.internal.processors.service.GridServiceProxy.invokeMethod(GridServiceProxy.java:197)
	at org.apache.ignite.internal.processors.service.GridServiceProxy$ProxyInvocationHandler.invoke(GridServiceProxy.java:345)
	at com.sun.proxy.$Proxy34.scheduleVehicleMaintenance(Unknown Source)
	at app.TestAppStartup.main(TestAppStartup.java:91)
Caused by: class org.apache.ignite.IgniteCheckedException: null
	at org.apache.ignite.internal.util.IgniteUtils.cast(IgniteUtils.java:7239)
	at org.apache.ignite.internal.util.future.GridFutureAdapter.get0(GridFutureAdapter.java:170)
	at org.apache.ignite.internal.util.future.GridFutureAdapter.get(GridFutureAdapter.java:119)
	at org.apache.ignite.internal.processors.service.GridServiceProxy.invokeMethod(GridServiceProxy.java:180)
	... 3 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ignite.internal.processors.service.GridServiceProxy$ServiceProxyCallable.call(GridServiceProxy.java:406)
	at org.apache.ignite.internal.processors.closure.GridClosureProcessor$C2V2.execute(GridClosureProcessor.java:2056)
	at org.apache.ignite.internal.processors.job.GridJobWorker$2.call(GridJobWorker.java:560)
	at org.apache.ignite.internal.util.IgniteUtils.wrapThreadLoader(IgniteUtils.java:6618)
	at org.apache.ignite.internal.processors.job.GridJobWorker.execute0(GridJobWorker.java:554)
	at org.apache.ignite.internal.processors.job.GridJobWorker.body(GridJobWorker.java:483)
	at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:110)
	at org.apache.ignite.internal.processors.job.GridJobProcessor.processJobExecuteRequest(GridJobProcessor.java:1180)
	at org.apache.ignite.internal.processors.job.GridJobProcessor$JobExecutionListener.onMessage(GridJobProcessor.java:1894)
	at org.apache.ignite.internal.managers.communication.GridIoManager.invokeListener(GridIoManager.java:1222)
	at org.apache.ignite.internal.managers.communication.GridIoManager.processRegularMessage0(GridIoManager.java:850)
	at org.apache.ignite.internal.managers.communication.GridIoManager.access$2100(GridIoManager.java:108)
	at org.apache.ignite.internal.managers.communication.GridIoManager$7.run(GridIoManager.java:790)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.ignite.cache.CachePartialUpdateException: Failed to update keys (retry update if possible).: [1]
	at org.apache.ignite.internal.processors.cache.GridCacheUtils.convertToCacheException(GridCacheUtils.java:1429)
	at org.apache.ignite.internal.processors.cache.IgniteCacheProxy.cacheException(IgniteCacheProxy.java:2182)
	at org.apache.ignite.internal.processors.cache.IgniteCacheProxy.put(IgniteCacheProxy.java:1382)
	at services.maintenance.MaintenanceServiceImpl.scheduleVehicleMaintenance(MaintenanceServiceImpl.java:104)
	... 20 more
Caused by: class org.apache.ignite.internal.processors.cache.CachePartialUpdateCheckedException: Failed to update keys (retry update if possible).: [1]
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridNearAtomicSingleUpdateFuture.onResult(GridNearAtomicSingleUpdateFuture.java:229)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.processNearAtomicUpdateResponse(GridDhtAtomicCache.java:3199)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.access$1700(GridDhtAtomicCache.java:126)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache$7.apply(GridDhtAtomicCache.java:356)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache$7.apply(GridDhtAtomicCache.java:351)
	at org.apache.ignite.internal.processors.cache.GridCacheIoManager.processMessage(GridCacheIoManager.java:827)
	at org.apache.ignite.internal.processors.cache.GridCacheIoManager.onMessage0(GridCacheIoManager.java:369)
	at org.apache.ignite.internal.processors.cache.GridCacheIoManager.handleMessage(GridCacheIoManager.java:293)
	at org.apache.ignite.internal.processors.cache.GridCacheIoManager.access$000(GridCacheIoManager.java:95)
	at org.apache.ignite.internal.processors.cache.GridCacheIoManager$1.onMessage(GridCacheIoManager.java:238)
	at org.apache.ignite.internal.managers.communication.GridIoManager.invokeListener(GridIoManager.java:1222)
	at org.apache.ignite.internal.managers.communication.GridIoManager.processRegularMessage0(GridIoManager.java:850)
	at org.apache.ignite.internal.managers.communication.GridIoManager.access$2100(GridIoManager.java:108)
	at org.apache.ignite.internal.managers.communication.GridIoManager$7.run(GridIoManager.java:790)
	at org.apache.ignite.internal.util.StripedExecutor$Stripe.run(StripedExecutor.java:428)
	... 1 more
	Suppressed: class org.apache.ignite.IgniteCheckedException: Failed to update keys on primary node.
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridNearAtomicUpdateResponse.addFailedKey(GridNearAtomicUpdateResponse.java:350)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.updateSingle(GridDhtAtomicCache.java:2620)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.updateAllAsyncInternal0(GridDhtAtomicCache.java:1881)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.updateAllAsyncInternal(GridDhtAtomicCache.java:1721)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.processNearAtomicUpdateRequest(GridDhtAtomicCache.java:3181)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.access$1600(GridDhtAtomicCache.java:126)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache$6.apply(GridDhtAtomicCache.java:338)
		at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache$6.apply(GridDhtAtomicCache.java:333)
		... 11 more
		Suppressed: class org.apache.ignite.IgniteCheckedException: Cache store must work with binary objects if binary are enabled for cache [cacheName=maintenance]
			at org.apache.ignite.internal.processors.cache.store.GridCacheStoreManagerAdapter.handleClassCastException(GridCacheStoreManagerAdapter.java:811)
			at org.apache.ignite.internal.processors.cache.store.GridCacheStoreManagerAdapter.put(GridCacheStoreManagerAdapter.java:584)
			at org.apache.ignite.internal.processors.cache.GridCacheMapEntry.innerUpdate(GridCacheMapEntry.java:2507)
			at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.updateSingle(GridDhtAtomicCache.java:2479)
			... 17 more
		Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
			at common.cachestore.SimpleCacheStore.write(SimpleCacheStore.java:52)
			at org.apache.ignite.internal.processors.cache.store.GridCacheStoreManagerAdapter.put(GridCacheStoreManagerAdapter.java:579)
			... 19 more
```

**Comment by dmagda** [comment]
Guys, I couldn't reproduce the issue on my side.

Anyway, updated the Ignite version to 2.3 making sure the project works on the latest stable Ignite version. Pull the changes and make sure you execute the example in the following order:

- Start one or more instances of data nodes using DataNodeStartup.
- Start one or more instances of Maintenance service nodes using MaintenanceServiceNodeStartup.
- Start one or more instances of Vehicle service nodes using VehicleServiceNodeStartup.
- Execute an internal test application (connects to the microservices using Ignite API) using TestAppStart.
